# Exception tests.

test_check_success(AssertNoExcept)

